### ISSUE TITLE
Wrong test is mentioned in this lab

### ISSUE THREAD

**Issue by JamilaGastar** [learn-co-curriculum/phase-0-html-experiencing-html-lab#19]
Hello,
This lab mentions to use respec however the test in this one uses npm install and npm test.

**Comment by lizbur10** [comment]
Hi @JamilaGastar - thank you for bringing this to our attention.

All of the labs in the prework have been updated to use Mocha rather than Rspec for testing. Unfortunately, for students in older prework courses, we are not able to update the instructions in Canvas because some of the changes we made would cause problems for students who were partway through the prework. 

For all prework labs, you should use `npm install` to install dependencies and `npm test` to run the tests, and ignore any instructions you see to use `bundle` or `rspec`.

Apologies for the inconvenience 💙
