### ISSUE TITLE
Run Bundle and rspec

### ISSUE THREAD

**Issue by Dcolonel6** [learn-co-curriculum/phase-0-html-experiencing-html-lab#23]
How are we suppose to run bundle on a project written in js?. On Canvas the instructions are ```cd into the repository that you just cloned down in the terminal, then run code . to open the files in Visual Studio Code. (If you are using a different text editor, the command will be different. For the AWS Cloud9 IDE, for example, you must click on the file in the left navigation to open it.) Finally, run bundle to install the lab's dependencies.

Note: **This lab's test uses Ruby**, so the commands we'll use are different than what you've seen before — npm install and npm test. Here, we use bundle and rspec to do the same things. The bundle command installs the Ruby dependencies for this lab, and you only need to run it once. You can run rspec any time you want to run the tests.```

No the lab test are written in js and running the npm install and npm test will get you through the assignment.

**Comment by lizbur10** [comment]
Hi @Dcolonel6 - it looks like you may be in an older prework course. Substantial updates and reorganization were made to the prework a while back and, unfortunately, we were not able to update older prework courses because some of the updates would have caused breaking changes for students who had already started the prework. The GitHub repos that your lessons are tied to, however, **have** been updated, which is why you see this inconsistency. 

As you continue through the prework, you should just continue to run `npm install` and `npm test` and disregard any conflicting instructions. 

Apologies for the inconvenience and thanks for contributing to the Flatiron School curriculum 💙
