### ISSUE TITLE
Use of rspec and bundle instead of npm install and npm run test.

### ISSUE THREAD

**Issue by ElikanahMasanta** [learn-co-curriculum/phase-0-html-experiencing-html-lab#26]
With the information in canvas, it suggests one to use bundle, then rspec commands to test the passing of (my_lisy.html). But with the use of this, I was getting an error(zsh: command not found: rspec). So I tried with the npm install and npm run test and I was able to successfully test.

**Comment by lizbur10** [comment]
Hi @ElikanahMasanta - thank you for bringing this to our attention.

All of the labs in the prework have been updated to use Mocha rather than Rspec for testing. Unfortunately, for students in older prework courses, we are not able to update the instructions in Canvas because some of the other changes we made would cause problems for students who were partway through the prework.

For all prework labs, you should use npm install to install dependencies and npm test to run the tests, and ignore any instructions you see to use bundle or rspec.

Apologies for the inconvenience 💙
