### ISSUE TITLE
Assignment failed to submit.

### ISSUE THREAD

**Issue by LoiseKimani** [learn-co-curriculum/phase-0-html-experiencing-html-lab#30]

**Comment by lizbur10** [comment]
Thanks for raising this issue. Based on your description, it sounds like this issue may be related to Canvas rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
